// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var BignumberJs = require("bignumber.js");

function decodeString(param) {
  return Json_decode.map((function (prim) {
                return new BignumberJs(prim);
              }), Json_decode.string, param);
}

function decodeInt(param) {
  return Json_decode.map((function (prim) {
                return new BignumberJs(prim);
              }), Json_decode.$$int, param);
}

function decodeFloat(param) {
  return Json_decode.map((function (prim) {
                return new BignumberJs(prim);
              }), Json_decode.$$float, param);
}

var partial_arg_001 = /* :: */[
  decodeInt,
  /* :: */[
    decodeFloat,
    /* [] */0
  ]
];

var partial_arg = /* :: */[
  decodeString,
  partial_arg_001
];

function decodeAny(param) {
  return Json_decode.oneOf(partial_arg, param);
}

function encode(d) {
  return d.toJSON();
}

exports.decodeString = decodeString;
exports.decodeInt = decodeInt;
exports.decodeFloat = decodeFloat;
exports.decodeAny = decodeAny;
exports.encode = encode;
/* bignumber.js Not a pure module */
